version: '3'

services:
  master:
    image: locust
    ports:
     - "8089:8089"
    command: -f /mnt/locust/locustfile.py --master
  
  worker:
    image: locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master